using System;

namespace MyApplication
{
  class Program
  {
    static void Main(string[] args)
    {
    //Delcare The Values
      int userAge;
      
      
      //assign
      userAge = 23;
      //Had to make this 23 because get next input doesnt exist in C#
      
      
      
      
      
      //Output
      Console.WriteLine(userAge);
      Console.WriteLine(" is a great age");

     }
  }
}
// THIS IS NOT DONE, PLEASE FINISH.
//FOR CONTEXT, GET NEXT INPUT DOESNT EXIST IN C#